name: Test shell commands

on: [push]

jobs:
  get-changed-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          token: ${{ secrets.TOK }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: List all changed files
        run: |
          DIRS_ALL=''
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            # we get config dir
            if [[ "$file" == *"config.yml" ]]; then
              DIR="${file: :-10}"
            elif [[ "$file" == *".env" ]]; then
              DIR="${file: :-4}"
            else
              continue
            fi
            # we skip if dir is already considered by any file change
            if [[ "$DIRS_ALL" == *"$DIR"* ]]; then
              continue
            else
              DIRS_ALL="$DIRS_ALL $DIR"
            fi
            echo "This is file: $file in $DIR"
            export $(grep 'PROMETHEUS_HOSTNAME=' ${DIR}.env | xargs)
            docker build . --build-arg dir=$DIR -t ashiful/kaktarua:${PROMETHEUS_HOSTNAME}
            docker push ashiful/kaktarua:${PROMETHEUS_HOSTNAME}
          done
          docker images
